### ISSUE TITLE
<none>

### ISSUE THREAD

**Issue by Solution97** [rplcnn/SuperSmash#1]
Everywhere is standing none can do nothing

**Comment by rplcnn** [comment]
Did you install Smash-Files?

**Comment by Solution97** [comment]
```
[13:03:03] [pool-3-thread-15/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Checking for the latest version of Skript...[m
[13:03:04] [Skript update thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m You're currently running the latest stable version of Skript.[m
[13:03:04] [Server thread/ERROR]: [Skript] Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (Smash-Files.sk, line 292: wf "  set {No_Permission_Kit} to ""&cNo permission for this kit!""" to "plugins/SuperSmash/messages.sk')
[13:03:05] [Server thread/WARN]: [Skript] Empty configuration section! You might want to indent one or more of the subsequent lines to make them belong to this section or remove the colon at the end of the line if you don't want this line to start a section. (Smash-Main.sk, line 469: wait 1 ticks:')
[13:03:10] [Server thread/ERROR]: [Skript] 'wait 1 ticks' is not a boolean (yes/no) (Smash-Main.sk, line 469: wait 1 ticks:')
[13:03:16] [Server thread/INFO]: [0;32;22m[[0;32;1mSmash[0;32;22m][0;37;22m <none>[m
[13:03:18] [Server thread/ERROR]: [Skript] 'radius 5' is not an entity type (Smash-Main.sk, line 2219: loop items in radius 5:')
[13:03:18] [Server thread/WARN]: [Skript] Task #16 for Skript v2.1.2 generated an exception
java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/FactionColls
    at ch.njol.skript.hooks.regions.Factions2Hook.getRegion_i(Factions2Hook.java:214) ~[?:?]
    at ch.njol.skript.hooks.regions.RegionsPlugin.getRegion(RegionsPlugin.java:105) ~[?:?]
    at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:84) ~[?:?]
    at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:1) ~[?:?]
    at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:398) ~[?:?]
    at ch.njol.skript.registrations.Classes.parse(Classes.java:427) ~[?:?]
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
    at ch.njol.skript.effects.EffChange.init(EffChange.java:209) ~[?:?]
    at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:237) ~[?:?]
    at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:164) ~[?:?]
    at ch.njol.skript.lang.Statement.parse(Statement.java:42) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:615) ~[?:?]
    at ch.njol.skript.lang.Loop.<init>(Loop.java:74) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:651) ~[?:?]
    at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55) ~[?:?]
    at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:701) ~[?:?]
    at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55) ~[?:?]
    at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:701) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:489) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239) ~[?:?]
    at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193) ~[?:?]
    at ch.njol.skript.Skript$2.run(Skript.java:378) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680) [craftbukkit.jar:git-Bukkit-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit.jar:git-Bukkit-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit.jar:git-Bukkit-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit.jar:git-Bukkit-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.FactionColls
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_79]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-18fbb24]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-18fbb24]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
    ... 33 more
[13:03:18] [pool-3-thread-14/INFO]: [Vault] Checking for Updates ... 
[13:03:19] [pool-3-thread-14/INFO]: [Vault] No new version available
[13:03:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 17455ms behind, skipping 349 tick(s)
[13:03:22] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Reloading [0;33;22mSmash-Files.sk[m...[m
[13:03:22] [Server thread/ERROR]: Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (Smash-Files.sk, line 292: wf "   set {No_Permission_Kit} to ""&cNo permission for this kit!""" to "plugins/SuperSmash/messages.sk')
[13:03:22] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m [0;31;22mEncountered 1 error while reloading [0;33;22mSmash-Files.sk[m![m
[13:03:28] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7130ms behind, skipping 142 tick(s)
[13:03:30] [Server thread/INFO]: [ChatEx] There is no new version available. You are up-to-date!
[13:03:49] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7095ms behind, skipping 141 tick(s)
[13:04:22] [User Authenticator #1/INFO]: UUID of player SoLuTiioN is cc4883be-e388-4131-ab07-15aa52eb4323
[13:04:23] [Server thread/INFO]: SoLuTiioN[/94.166.25.11:2499] logged in with entity id 5163 at ([world]155.5247828431966, 70.0, 354.50169049341855)
[13:04:23] [pool-3-thread-16/INFO]: [GAListener] Player: SoLuTiioN has 3 votes
[13:04:24] [Server thread/INFO]: [ChatEx] There is no new version available. You are up-to-date!
```

**Comment by Solution97** [comment]
I installed the 3 required Plugins
I puted the 3 .sk files of your Plugin in the Skript/skripts folder and restartet the Server

Here my files:

plugins/Skript/scripts -> https://gyazo.com/fa781b9d555c8002814159ea63607598

**Comment by Solution97** [comment]
when i do /smash create <name> i get an emerald and i can open the menu but all menupointsnames are none

**Comment by rplcnn** [comment]
Thanks for bugs. I'm working on it.

**Comment by Solution97** [comment]
No Problem :) but i see its going to be a nice plugin :)
Please tell me here when you have updated the Plugin! :D
